### ISSUE TITLE
Site Crash when not selecting a CSV to upload

### ISSUE THREAD

**Issue by leestott** [martinkearn/Azure-pass-manager#1]
Error 

Azure Pass Manager
Issues / Feedback?
Upload Codes
Events
Hello ******@****.com!
Sign out
Error.
An error occurred while processing your request.
Request ID: 0HL8BTOBIO808:00000006 
Development Mode
Swapping to Development environment will display more detailed information about the error that occurred. 
Development environment should not be enabled in deployed applications, as it can result in sensitive information from exceptions being displayed to end users. For local debugging, development environment can be enabled by setting the ASPNETCORE_ENVIRONMENT environment variable to Development, and restarting the application. 

To Replicate this simply  add event name, date and then press upload without selecting a CSV/Upload file

**Comment by martinkearn** [comment]
Just fixed this and re-published the site. It should not let your press the button unless fields have values
