### ISSUE TITLE
Event Details page - do show all the details just event name

### ISSUE THREAD

**Issue by leestott** [martinkearn/Azure-pass-manager#10]
At present your showing 

Owner ****@****.com 
Expiry MM/DD/2017 
Codes available ****

I think you should just have Expiry Date only as event organisers don't want to give their emails to attendees as they may ask for more codes etc. in terms of codes the following codes are available ($100/6 month) or $50/1 Month) 

In terms of Expiry I think this should be the following txt on http://apm-web.azurewebsites.net/event/***********

Welcome to *********

We're about to give you an Azure trial code.

These codes give you $**** of free Azure credits.  

Only claim a code if you plan to use it. We have a limited number and we'll assume the code has been claimed as soon as we show it to you. 

Codes need to be redeemed before this date DD/MM/YYYY 

Claim your code

**Comment by martinkearn** [comment]
Thanks Lee. All sounds ok apart from 

"$****" because we do not gather information about the value of the codes at upload (I may add that specific feature as its own issue)

**Comment by martinkearn** [comment]
The page has now been updated to address the above
