### ISSUE TITLE
Have a way to mark a code and un-used after it has been claimed

### ISSUE THREAD

**Issue by martinkearn** [martinkearn/Azure-pass-manager#3]
There may be scenarios where a delegate claims a code which they do not use and you may want to return it to the pool of unused codes for an event.

There should be a way to mark a 'used' code as 'unused' as an administrator

**Comment by martinkearn** [comment]
Work in progress. Have a way to GET and PUT codes and have Details view but not yet Edit views

**Comment by leestott** [comment]
Martin not sure this a significant issue as unclaimed codes are troublesome as all codes expire automatically 90 days after allocation. again at an event if someone says I don't want this code you can add it manually back into the system?

**Comment by martinkearn** [comment]
Hi Lee, this issue is to address the "I don't need this code any more" scenario. Currently there is no way to add a single code back in so editing its status seems like a better approach.

**Comment by martinkearn** [comment]
Fixed in this commit: https://github.com/martinkearn/Azure-pass-manager/commit/ea04df0812b0438c47a18d8ffa720714aa93c89e
